#!/usr/bin/php
<?php
/**
 * Copyleft (c) 2013 Pierre Cassat and contributors
 * <www.ateliers-pierrot.fr> - <contact@ateliers-pierrot.fr>
 * License GPL-3.0 <http://www.opensource.org/licenses/gpl-3.0.html>
 * Sources <https://github.com/atelierspierrot/atelierspierrot>
 * 
 * console/dir-cleaner
 *
 * Delete a collection of unwanted OS or software files in a directory, recursively
 * 
 * For more infos run:
 * 
 *     ~$ php path/to/dir-cleaner -h
 * 
 */
@ini_set('display_errors','1'); @error_reporting(E_ALL ^ E_NOTICE);

define('_AP_SCRIPT_VERSION', '1.0.0');
define('_AP_SCRIPT_NAME', 'Recursive directory cleaner');
define('_AP_SCRIPT_AUTHOR', 'Les Ateliers Pierrot <www.ateliers-pierrot.fr>');
define('_AP_SCRIPT_FILENAME', basename(__FILE__));
define('_AP_SCRIPT_DIR', __DIR__);
define('_AP_CONSOLE_LIBRARY', __DIR__.'/console_lib.php');

// -------------------
// requirements
// -------------------

if (@file_exists(_AP_CONSOLE_LIBRARY)) {
    include_once _AP_CONSOLE_LIBRARY;
} else {
    die('The library "console_lib.php" is required in the same directory as this script!'."\n");
}
cliOnly();

// -------------------
// defaults
// -------------------

global $files_collection, $path, $dry;
$files_collection = array(
    '._*', '.DS_Store', '*~', 'Thumbs.db', 'ehthumbs.db', 'Icon'
);
$path='.';
$dry=false;

// -------------------
// library
// -------------------

function writeHelp()
{
    global $files_collection;
    write();
    writeBold('Presentation');
    write('  Shell script to delete a collection of specific operating systems or software internal files in a directory content and its sub-directories.');
    write();
    writeBold('Usage');
    write('    ~$ '.getBold('php '._AP_SCRIPT_FILENAME.' -[option[=value]]'));
    write();
    writeBold('Basic options');
    writeList(array(
        'p=path' => 'path to the working root directory, absolute path or relative to `cwd` (default is `.`, the current directory)',
        'c="coll ection"' => 'the collection of filenames masks to delete (space separated, you must surround your list between double-quotes)',
        'd'=>'dry run: writes the list of matched files but doesn\'t execute the deletions',
    ), '    %s    %s');
    write();
    writeBold('Default files list');
    write('    '.implode('    ', $files_collection));
    write();
}

// -------------------
// options treatments
// -------------------

function runHelp()
{
    writeTitle();
    writeHelp();
    exit(0);
}

function runCollection($collection)
{
    global $files_collection;
    $files_collection = explode(' ', $collection);
    array_filter($files_collection);
}

function runDry()
{
    global $dry;
    $dry = true;
}

function runPath($_path)
{
    global $path;
    $path = $_path;
}

function run()
{
    global $files_collection, $path, $dry;

    if (file_exists($path)) {
        foreach(scandir($path) as $key=>$subdir) {
            if (!in_array($subdir, array('.', '..'))) {

                $data[$subdir] = getLocalRepoInfos(rtrim($path, '/').'/'.$subdir);

            }
        }
    } else {
        trigger_error(sprintf('Directory "%s" not found!', $path), E_USER_ERROR);
    }
}

// -------------------
// script execution
// -------------------

// arguments
$args = array(
    'h'=>'help',
    'c:'=>'collection',
    'p:'=>'path',
    'd'=>'dry',
);
$options = getopt( implode('', array_keys($args)) );

// if no option at all
if (empty($options)) {
    runHelp();
} else {
    foreach($options as $name=>$value) {
        if (isset($args[$name]) || isset($args[$name.':'])) {
            $argname = isset($args[$name.':']) ? $name.':' : $name;
            $_meth = 'run'.ucfirst($args[$argname]);
            $_arg = !empty($value) ? $value : null;
            if (function_exists($_meth)) {
                $_meth($_arg);
            } else {
                trigger_error('Unknown option "'.$name.'"!', E_USER_ERROR);
            }
        } else {
            trigger_error('Unknown option "'.$name.'"!', E_USER_ERROR);
        }
    }
}
run();
exit(0);
// Endfile
